#! /bin/sh

PATH=$PATH:$HOME/bin

LEMONBAR_HEIGHT=32

bspc config border_width        3
bspc config window_gap         15
bspc config top_padding        $LEMONBAR_HEIGHT

bspc config split_ratio         0.50
#bspc config borderless_monocle  true
#bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d browse dev term irc music files etc

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

pkill lemonbar
lemonbar_run $LEMONBAR_HEIGHT &
